title: Anjishnu Mukherjee
position: PhD student
affiliation: George Mason University
email: amukher6 (at) gmu (dot) edu
keywords: fairness nlp explainability
google_scholar: https://scholar.google.com/citations?hl=en&user=3849YpIAAAAJ
github_link: https://github.com/iamshnoo
linkedin: https://www.linkedin.com/in/anjishnumukherjee/
twitter: https://twitter.com/iamshnoo/
avatar: ./assets/img/profile_picture.jpg
google_analytics:
favicon: ./assets/img/profile_picture.jpg
favicon_dark: ./assets/img/profile_picture.jpg
description: My personal webpage.
canonical:
remote_theme: yaoyao-liu/minimal-light
