title: Anjishnu Mukherjee
position: Prospective Grad Student, Fall '22
affiliation: Data Science @ Wells Fargo
email: mukherjee.anjishnu (at) gmail.com
keywords: computer-vision nlp
google_scholar: https://scholar.google.com/citations?hl=en&user=3849YpIAAAAJ
github_link: https://github.com/iamshnoo
linkedin: https://www.linkedin.com/in/anjishnumukherjee/
twitter: https://twitter.com/iamshnoo/
resume: assets/pdf/Anjishnu_Mukherjee_cv.PDF
avatar: ./assets/img/profile_picture.jpg
google_analytics:
favicon: ./assets/img/profile_picture.jpg
favicon_dark: ./assets/img/profile_picture.jpg
description: My personal webpage.
canonical:
remote_theme: yaoyao-liu/minimal-light
